name: CI - API Flask

on:
  push:
  pull_request:

jobs:
  test:
    name: CI - API Flask
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: pip install -r aula5/requirements.txt

      - name: Rodar testes
        run: PYTHONPATH=. pytest aula5/

      - name: Simular Deploy
        run: echo "Deploy realizado com sucesso"